// Mirrors backend/app/core/permissions.py - used for conditional UI rendering.
// Note: this is ONLY a UI convenience. The backend is authoritative for access control.
export const PERMISSIONS = {
  EMPLOYEE_READ_SELF: 'employee.read_self',
  EMPLOYEE_READ_ALL: 'employee.read_all',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_ARCHIVE: 'employee.archive',
  CONTRACT_READ: 'contract.read',
  CONTRACT_CREATE: 'contract.create',
  CONTRACT_UPDATE: 'contract.update',
  SCHEDULE_MANAGE: 'schedule.manage',
  SCHEDULE_READ: 'schedule.read',
  ATTENDANCE_READ_SELF: 'attendance.read_self',
  ATTENDANCE_READ_ALL: 'attendance.read_all',
  ATTENDANCE_CREATE_SELF: 'attendance.create_self',
  ATTENDANCE_CORRECT: 'attendance.correct',
  TIMEOFF_REQUEST: 'timeoff.request',
  TIMEOFF_READ_ALL: 'timeoff.read_all',
  TIMEOFF_APPROVE: 'timeoff.approve',
  TIMEOFF_ALLOCATE: 'timeoff.allocate',
  TIMEOFF_CONFIGURE: 'timeoff.configure',
  SALARY_STRUCTURE_READ: 'salary_structure.read',
  SALARY_STRUCTURE_MANAGE: 'salary_structure.manage',
  SALARY_RULE_READ: 'salary_rule.read',
  SALARY_RULE_MANAGE: 'salary_rule.manage',
  PAYRUN_READ: 'payrun.read',
  PAYRUN_CREATE: 'payrun.create',
  PAYRUN_COMPUTE: 'payrun.compute',
  PAYRUN_VALIDATE: 'payrun.validate',
  PAYRUN_MARK_PAID: 'payrun.mark_paid',
  PAYRUN_SEND: 'payrun.send',
  PAYSLIP_READ_SELF: 'payslip.read_self',
  PAYSLIP_READ_ALL: 'payslip.read_all',
  PAYSLIP_PRINT: 'payslip.print',
  DASHBOARD_READ: 'dashboard.read',
  USER_MANAGE: 'user.manage',
  ROLE_MANAGE: 'role.manage',
}
